In [ ]:
from mlp.test_methods import test_dropout_layer
import numpy as np
fprop_test, fprop_output, fprop_correct, \
bprop_test, bprop_output, bprop_correct = test_dropout_layer()

assert fprop_test == 1.0, (
'The dropout layer fprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct, fprop_output, fprop_output-fprop_correct)
)

print("Dropout Layer Fprop Functionality Test Passed")

assert bprop_test == 1.0, (
'The dropout layer bprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct, bprop_output, bprop_output-bprop_correct)
)

print("Dropout Layer Bprop Test Passed")

In [3]:
from mlp.test_methods import test_L1_Penalty


call_test, call_output, call_correct, \
grad_test, grad_output, grad_correct = test_L1_Penalty()


assert call_test == 1.0, (
'The call function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(call_correct, call_output, call_output-call_correct)
)

print("L1 Penalty Call Functionality Test Passed")

assert grad_test == 1.0, (
'The grad function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grad_correct, grad_output, grad_output-grad_correct, grad_output/grad_correct)
)



print("L1 Penalty Grad Function Test Passed")

L1 Penalty Call Functionality Test Passed


AssertionError: The grad function for L1 Penalty test failedCorrect output is 

[[[[-0.0001 -0.0001  0.0001 ... -0.0001  0.0001 -0.0001]
   [-0.0001  0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   ...
   [-0.0001  0.0001  0.0001 ...  0.0001 -0.0001 -0.0001]
   [ 0.0001  0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]]

  [[-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001  0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001 -0.0001  0.0001 ...  0.0001 -0.0001  0.0001]
   ...
   [ 0.0001  0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]]

  [[-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001  0.0001 ... -0.0001 -0.0001  0.0001]
   [ 0.0001  0.0001 -0.0001 ... -0.0001  0.0001  0.0001]
   ...
   [ 0.0001  0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]
   [ 0.0001 -0.0001  0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001  0.0001  0.0001]]]


 [[[-0.0001 -0.0001  0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001  0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]
   ...
   [ 0.0001  0.0001 -0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001 -0.0001  0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001  0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]]

  [[-0.0001 -0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   ...
   [-0.0001  0.0001  0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]]

  [[-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [-0.0001 -0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   [ 0.0001 -0.0001  0.0001 ...  0.0001  0.0001  0.0001]
   ...
   [ 0.0001  0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [ 0.0001 -0.0001  0.0001 ...  0.0001 -0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]]]


 [[[-0.0001  0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [ 0.0001  0.0001  0.0001 ...  0.0001  0.0001  0.0001]
   [ 0.0001 -0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   ...
   [ 0.0001  0.0001  0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001  0.0001  0.0001 ...  0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]]

  [[-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   ...
   [-0.0001  0.0001  0.0001 ...  0.0001  0.0001  0.0001]
   [-0.0001 -0.0001  0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001  0.0001  0.0001]]

  [[ 0.0001 -0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001  0.0001  0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001 -0.0001 ... -0.0001  0.0001  0.0001]
   ...
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]]]


 ...


 [[[ 0.0001  0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001 -0.0001  0.0001 ...  0.0001  0.0001  0.0001]
   ...
   [ 0.0001 -0.0001  0.0001 ... -0.0001  0.0001 -0.0001]
   [-0.0001  0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001  0.0001 ... -0.0001  0.0001 -0.0001]]

  [[-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [ 0.0001  0.0001 -0.0001 ... -0.0001  0.0001  0.0001]
   [ 0.0001  0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   ...
   [ 0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]]

  [[-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [-0.0001 -0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   ...
   [ 0.0001 -0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   [ 0.0001 -0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]]]


 [[[-0.0001 -0.0001  0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001  0.0001]
   ...
   [-0.0001  0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]]

  [[-0.0001  0.0001 -0.0001 ...  0.0001 -0.0001 -0.0001]
   [-0.0001  0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001 -0.0001  0.0001]
   ...
   [-0.0001 -0.0001  0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [ 0.0001  0.0001  0.0001 ...  0.0001  0.0001 -0.0001]]

  [[-0.0001 -0.0001 -0.0001 ... -0.0001  0.0001  0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [ 0.0001 -0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   ...
   [ 0.0001  0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001  0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [ 0.0001 -0.0001  0.0001 ... -0.0001  0.0001 -0.0001]]]


 [[[ 0.0001  0.0001 -0.0001 ... -0.0001  0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   ...
   [-0.0001  0.0001  0.0001 ... -0.0001  0.0001  0.0001]
   [ 0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001  0.0001 ... -0.0001 -0.0001  0.0001]]

  [[ 0.0001  0.0001 -0.0001 ...  0.0001 -0.0001  0.0001]
   [ 0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   [ 0.0001  0.0001  0.0001 ... -0.0001 -0.0001 -0.0001]
   ...
   [-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001  0.0001]
   [-0.0001  0.0001  0.0001 ... -0.0001 -0.0001  0.0001]
   [-0.0001  0.0001  0.0001 ... -0.0001 -0.0001  0.0001]]

  [[ 0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ... -0.0001 -0.0001 -0.0001]
   ...
   [-0.0001  0.0001  0.0001 ...  0.0001  0.0001 -0.0001]
   [-0.0001  0.0001  0.0001 ... -0.0001  0.0001 -0.0001]
   [-0.0001 -0.0001 -0.0001 ...  0.0001  0.0001  0.0001]]]]

 but returned output is 

-0.11560000000000001

 difference is 

[[[[-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1155]
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1157]
   ...
   [-0.1155 -0.1157 -0.1157 ... -0.1157 -0.1155 -0.1155]
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1155 ... -0.1155 -0.1157 -0.1155]]

  [[-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1157]
   ...
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]]

  [[-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1155 -0.1157]
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1155]
   [-0.1157 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1157 -0.1157]]]


 [[[-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1155]
   ...
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1155]]

  [[-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   ...
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1157]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1157]]

  [[-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1155 -0.1155]
   [-0.1157 -0.1155 -0.1157 ... -0.1157 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1157 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1155]]]


 [[[-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1157 -0.1157 -0.1157 ... -0.1157 -0.1157 -0.1157]
   [-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1157 -0.1157 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1157 -0.1157 ... -0.1157 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1155 -0.1157]]

  [[-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   ...
   [-0.1155 -0.1157 -0.1157 ... -0.1157 -0.1157 -0.1157]
   [-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1157 -0.1157]]

  [[-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1157 -0.1157 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1155 ... -0.1155 -0.1157 -0.1157]
   ...
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]]]


 ...


 [[[-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1155]
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1155]]

  [[-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1157]
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1155 -0.1155]]

  [[-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1155 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1155]
   ...
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1155 -0.1155]
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]]]


 [[[-0.1155 -0.1155 -0.1157 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1157]
   ...
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]]

  [[-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1155]
   [-0.1155 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1157]
   ...
   [-0.1155 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1157 -0.1157 -0.1157 ... -0.1157 -0.1157 -0.1155]]

  [[-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1157 -0.1157]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1157]
   ...
   [-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1157 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1157 -0.1155]]]


 [[[-0.1157 -0.1157 -0.1155 ... -0.1155 -0.1157 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]
   ...
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1157 -0.1157]
   [-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1157 ... -0.1155 -0.1155 -0.1157]]

  [[-0.1157 -0.1157 -0.1155 ... -0.1157 -0.1155 -0.1157]
   [-0.1157 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]
   [-0.1157 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1155]
   ...
   [-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1157]
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1157]
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1155 -0.1157]]

  [[-0.1157 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1155 -0.1155 -0.1155]
   ...
   [-0.1155 -0.1157 -0.1157 ... -0.1157 -0.1157 -0.1155]
   [-0.1155 -0.1157 -0.1157 ... -0.1155 -0.1157 -0.1155]
   [-0.1155 -0.1155 -0.1155 ... -0.1157 -0.1157 -0.1157]]]]

In [1]:
from mlp.test_methods import test_L1_Penalty


call_test, call_output, call_correct, \
grad_test, grad_output, grad_correct = test_L1_Penalty()


assert call_test == 1.0, (
'The call function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(call_correct, call_output, call_output-call_correct)
)

print("L1 Penalty Call Functionality Test Passed")

assert grad_test == 1.0, (
'The grad function for L1 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grad_correct, grad_output, grad_output-grad_correct, grad_output/grad_correct)
)



print("L1 Penalty Grad Function Test Passed")

L2 Penalty Call Functionality Test Passed


AssertionError: The grad function for L2 Penalty test failedCorrect output is 

[[[[-1.35289051e-05 -7.22695189e-04  8.02934585e-04 ... -7.22334541e-04
     4.23127441e-04 -2.98171099e-04]
   [-8.98062275e-04  3.28718559e-04  2.23723816e-04 ... -1.11504965e-04
    -3.65918552e-04 -2.00610212e-04]
   [-2.77196357e-04 -2.99592775e-06  2.01446867e-04 ... -6.06706357e-06
     9.82900325e-05  7.02203442e-04]
   ...
   [-3.86832003e-04  3.19751012e-04  2.94174351e-05 ...  2.42161552e-04
    -1.31351039e-04 -1.07832418e-04]
   [ 1.88564329e-04  8.18030614e-04 -1.67724881e-04 ... -4.89743919e-04
    -1.01603113e-03  3.19572096e-04]
   [ 1.39727817e-04 -4.05792012e-05 -1.52506667e-04 ... -8.31521767e-05
     7.84694152e-04 -5.43952913e-04]]

  [[-1.12106463e-04 -5.49818912e-04 -5.04150598e-05 ...  3.54715117e-04
     1.88164097e-04 -1.99439667e-04]
   [ 9.08420767e-05 -4.51439923e-04  4.51945863e-05 ...  9.35304664e-05
    -6.15112813e-04  4.54552899e-04]
   [-3.14721506e-04 -9.16064107e-04  8.50434291e-04 ...  5.59019109e-04
    -4.64417457e-04  7.45061830e-04]
   ...
   [ 3.66168821e-04  3.54842275e-04  9.07283253e-05 ... -6.72920287e-04
     1.02925781e-04  6.38424856e-04]
   [-1.27176407e-04  8.05269816e-04 -2.11809023e-04 ...  2.89581547e-04
    -1.48944898e-04  4.83832514e-04]
   [-3.68302162e-04  4.38462736e-04 -5.18595743e-04 ...  8.04372789e-04
    -1.18137850e-03  1.58410116e-05]]

  [[-9.89442095e-04 -2.52726264e-04 -3.78991556e-04 ... -8.74357681e-04
    -2.58905304e-04 -6.64930175e-04]
   [-2.19099413e-04 -1.48517479e-04  2.16344949e-04 ... -1.42675655e-07
    -5.87223946e-05  3.38062835e-04]
   [ 6.65002817e-04  1.54060268e-04 -7.91434106e-04 ... -1.24158031e-04
     2.77541849e-04  2.03223870e-04]
   ...
   [ 6.75382151e-04  8.36132126e-05 -9.67865890e-05 ...  6.36777671e-04
    -7.06702579e-04 -7.15571670e-05]
   [ 2.98489944e-04 -1.81608154e-04  2.40528433e-04 ...  1.43678581e-04
    -1.53086555e-04  3.15720643e-04]
   [-3.24743944e-04 -4.64188967e-04 -4.59182806e-05 ... -4.28140426e-04
     2.04722505e-05  5.34572639e-04]]]


 [[[-1.05345426e-03 -7.75123717e-04  3.23891068e-04 ...  1.03277725e-04
     1.13569778e-04 -1.86227619e-04]
   [ 7.31860043e-04  8.78094858e-04 -2.03846054e-04 ...  5.87674751e-04
    -4.66783243e-04 -7.66614739e-04]
   [-8.31002317e-05  9.64408531e-04 -3.80302265e-04 ... -8.56012839e-04
     2.89661248e-04 -1.77879338e-04]
   ...
   [ 2.47899382e-04  6.91947522e-04 -4.95540305e-04 ... -2.01378197e-04
     1.02932206e-03  3.23899112e-04]
   [-5.33863445e-04 -7.81388019e-04  4.70468091e-04 ...  2.44642132e-04
    -1.79708023e-04 -1.40877013e-04]
   [-1.57441873e-04  6.18144894e-05 -2.78689150e-04 ... -2.04494916e-04
     1.74076016e-04 -5.78559099e-04]]

  [[-4.17383646e-04 -3.32650321e-04  2.72405827e-05 ... -2.74398942e-04
     5.06089779e-04  6.37938511e-04]
   [-3.60245416e-04  8.84087064e-04 -5.16543302e-04 ...  3.41655475e-05
     1.46902878e-04 -5.90953612e-04]
   [ 1.58647094e-04 -4.45904893e-04 -4.33308880e-04 ...  6.22963519e-04
     1.17029440e-03 -1.76341020e-04]
   ...
   [-5.60115982e-04  1.42462583e-04  1.43074413e-04 ... -2.54773309e-04
     5.75440864e-04 -3.44778608e-04]
   [ 3.25599094e-04  9.09727985e-04 -5.70468863e-04 ... -1.51286193e-04
    -3.18904646e-04  4.14078809e-04]
   [-7.61699015e-05 -3.49509732e-04 -8.61749027e-05 ... -4.48857544e-05
    -3.23483469e-04  3.70083498e-05]]

  [[-6.43392063e-04 -1.69256985e-04 -4.81186151e-04 ...  2.15656250e-04
     1.04351744e-04 -7.44715205e-04]
   [-2.38250428e-04 -5.71513873e-05  3.93795080e-04 ... -4.08988716e-04
    -1.89590754e-04 -1.43888947e-04]
   [ 6.02946967e-04 -2.53561329e-04  2.67575691e-04 ...  1.22547745e-04
     1.23783937e-04  3.59402558e-04]
   ...
   [ 1.46702986e-04  2.42476650e-05 -1.97705214e-04 ...  4.43017828e-04
     5.35912745e-04  2.06418583e-04]
   [ 3.59640813e-04 -2.21789230e-04  9.08574108e-04 ...  5.44305561e-04
    -1.47063569e-04 -3.39298904e-04]
   [ 8.44998702e-04  7.25345481e-05  3.77505497e-04 ... -5.85003457e-04
    -9.40310689e-04 -2.10529851e-04]]]


 [[[-7.65824717e-04  6.19143398e-04 -8.71228229e-05 ...  2.40096433e-04
     2.73529237e-04  3.25695660e-04]
   [ 4.99773443e-04  7.57020123e-04  3.68952646e-04 ...  1.76039586e-04
     5.12923609e-04  7.87444769e-04]
   [ 3.14484426e-04 -1.26659184e-04 -1.14529620e-03 ...  1.50095710e-04
     9.60678137e-05  3.56746109e-05]
   ...
   [ 1.28554961e-03  2.96329558e-04  4.16435371e-04 ...  7.99585463e-05
    -3.50914964e-04 -6.48256979e-04]
   [-6.48876943e-04  9.55673951e-04  2.37247722e-04 ...  5.57941524e-04
    -3.73046859e-04  7.63709269e-04]
   [ 5.30541623e-04 -6.21704828e-04 -5.40761607e-04 ...  3.31742627e-05
    -1.18848834e-03  2.53063863e-05]]

  [[-1.49424469e-04  9.42439630e-04 -3.61902652e-04 ...  1.28673221e-04
    -1.22866381e-04  4.13367010e-04]
   [-4.49905857e-04  1.09301640e-03 -8.15516782e-04 ... -5.37070766e-04
     1.01178887e-04 -1.77146719e-05]
   [ 5.59063163e-04 -1.62993869e-04 -6.63597553e-04 ...  1.10077415e-04
     1.04367210e-03 -2.35705574e-04]
   ...
   [-1.75537243e-04  4.20309054e-05  8.87638949e-05 ...  1.86434374e-05
     2.65015843e-04  2.78890486e-04]
   [-1.01448023e-04 -9.32116906e-05  5.77106102e-04 ...  1.91495600e-04
     4.77869849e-05 -6.71635826e-04]
   [ 4.27256895e-04  6.66170922e-05  2.17996915e-04 ... -3.44358537e-04
     6.14970621e-04  3.48168529e-04]]

  [[ 1.50851228e-04 -2.22758426e-04 -6.37167929e-04 ...  7.67303340e-05
    -7.18524776e-04  6.93856865e-05]
   [-8.16702626e-04  5.96933310e-04  7.07155294e-05 ...  2.29456434e-04
     5.95594553e-05 -4.68110555e-04]
   [ 2.07496588e-04 -2.75994134e-04 -8.41326480e-04 ... -3.11076400e-05
     1.65675385e-04  1.97072059e-04]
   ...
   [-1.31663315e-04 -2.80722039e-04 -1.39474590e-04 ... -3.59966627e-04
    -9.99253938e-04  4.34424720e-04]
   [ 2.03848923e-04 -4.47329995e-04 -1.28496177e-04 ...  7.67342628e-05
     6.29619502e-04  6.17240525e-04]
   [-5.83420765e-04 -1.18797797e-03 -2.84435421e-04 ... -7.24259321e-04
    -3.59618823e-04 -6.17956185e-04]]]


 ...


 [[[ 5.16153801e-05  2.87962931e-05 -4.10244225e-04 ... -8.28086561e-04
    -5.16005230e-04  2.39132651e-04]
   [ 5.00148271e-05 -4.53511059e-05  7.55371396e-04 ... -6.37272969e-04
     5.80672095e-04  9.79135767e-04]
   [-3.79011959e-04 -7.64310416e-04  2.27048070e-04 ...  7.56689645e-04
     2.56780194e-04  3.63028768e-04]
   ...
   [ 2.51066727e-04 -1.17593751e-03  3.87873002e-04 ... -1.01171938e-03
     3.79934631e-04 -6.58912124e-06]
   [-1.26778547e-03  4.20933149e-05 -4.07555688e-04 ... -5.64534156e-04
    -1.06273619e-03 -4.76985175e-04]
   [-5.53717460e-04 -2.56210757e-04  3.11857813e-04 ... -9.15193928e-04
     3.55980325e-04 -8.38534254e-04]]

  [[-2.26439173e-04 -4.94486697e-04 -1.60004753e-04 ...  5.17568765e-04
     1.17592672e-04  4.06724773e-06]
   [ 4.38805353e-04  5.84489237e-04 -1.63150159e-03 ... -1.60374910e-05
     1.19187132e-04  5.94991251e-04]
   [ 2.42198617e-04  7.85535901e-04 -2.55253698e-04 ...  1.16585179e-04
     1.22975627e-04  8.70106920e-05]
   ...
   [ 2.84803051e-04 -1.35700944e-03 -2.06035493e-05 ... -2.30122022e-04
    -7.47249447e-04  1.97742683e-04]
   [-8.25273181e-04  8.98272638e-04 -3.98151267e-04 ...  3.84583289e-05
    -6.92067370e-04 -6.18134822e-04]
   [-1.23303613e-04 -5.14117266e-04 -3.62737754e-04 ...  3.52098549e-04
    -3.51500707e-04 -5.52200847e-04]]

  [[-1.64059542e-04  2.18946632e-04 -8.51335529e-05 ...  1.13121939e-03
    -2.16614884e-05  3.32918841e-04]
   [-1.59804045e-04 -6.64050320e-04 -1.11810782e-04 ...  8.42991880e-04
    -6.12938961e-04 -6.06313191e-04]
   [ 2.43093747e-04  7.73837133e-05  3.89058145e-04 ... -4.18974771e-04
    -3.11455896e-04 -5.85606595e-04]
   ...
   [ 1.36270975e-06 -5.80896674e-04  2.15053169e-04 ... -2.03609565e-04
    -2.17940294e-04 -3.76368142e-04]
   [ 5.70434538e-04 -9.55431738e-04  6.02932600e-04 ... -1.09051541e-04
    -4.14361341e-04 -5.84049277e-05]
   [-2.64354763e-04 -2.89356264e-04 -1.66337966e-04 ... -6.06089300e-04
    -1.13797246e-03 -1.45641333e-04]]]


 [[[-1.73194575e-05 -6.53986650e-04  5.90927534e-04 ...  9.51965359e-04
    -1.72499548e-04 -7.04662829e-04]
   [-2.02263348e-05 -3.75319608e-04  2.78136702e-04 ... -5.79966662e-04
     1.53756658e-04  1.84562667e-04]
   [-4.09559708e-04 -5.21271839e-04 -8.64252981e-05 ... -1.80580458e-03
    -7.16434662e-05  8.90024387e-04]
   ...
   [-1.23179090e-04  4.44708742e-04 -2.06130324e-04 ... -4.35070638e-04
    -2.11592192e-04 -3.30310080e-05]
   [-5.91120832e-05 -2.45238375e-04 -7.80018997e-04 ... -3.55468922e-04
     6.31595185e-04 -1.90419626e-04]
   [ 1.11079156e-04 -2.21124976e-04 -5.91895781e-05 ... -1.30071352e-03
    -6.08781806e-04 -6.65725411e-04]]

  [[-2.40078623e-04  2.61852352e-04 -7.95494794e-04 ...  3.15761212e-04
    -1.09827489e-03 -8.86671300e-04]
   [-7.49762623e-04  3.79007849e-04 -2.84254832e-04 ... -1.30242436e-04
     1.79969520e-04 -6.38945651e-04]
   [ 1.80359538e-04  3.06970243e-04  3.70540196e-04 ... -9.43281013e-05
    -7.79283986e-04  8.43523035e-04]
   ...
   [-6.56874724e-04 -1.21970171e-03  1.76880705e-04 ... -3.47742565e-04
     3.03270560e-04 -4.91482159e-04]
   [ 3.03629510e-04  2.41489845e-04 -4.08719882e-04 ...  9.00432819e-05
    -1.79863611e-04  1.07400698e-03]
   [ 3.61936847e-04  6.75065742e-04  7.36813625e-04 ...  1.37899730e-04
     4.73225337e-04 -7.19052374e-04]]

  [[-1.06340615e-05 -4.99736759e-05 -6.86004047e-04 ... -1.71181000e-04
     7.00557401e-04  2.94564198e-04]
   [-1.65373587e-04  1.67820813e-04 -3.40174539e-04 ...  1.11806973e-04
     4.83756732e-05  3.97660867e-04]
   [ 2.94490482e-04 -8.79982769e-05  2.18867109e-05 ... -5.06440230e-04
     1.21429961e-05  2.96678026e-05]
   ...
   [ 9.41295316e-05  2.01730610e-04 -1.60725272e-04 ... -8.26412152e-04
    -5.53923433e-05 -1.79791284e-04]
   [-7.65204484e-04  8.87981847e-04 -3.51457868e-04 ...  1.19735129e-04
     3.42208911e-04 -5.43409094e-04]
   [ 6.83847285e-04 -2.99072040e-04  3.76835017e-04 ... -1.65407493e-04
     8.96797730e-04 -4.86609540e-04]]]


 [[[ 4.68359185e-04  4.77985947e-04 -3.50177048e-04 ... -8.55359399e-04
     9.69742388e-05 -1.53865149e-05]
   [ 8.47649466e-05  2.07859416e-04  3.29884810e-04 ... -6.66916388e-04
    -6.70725651e-04 -1.39021979e-04]
   [-5.37983811e-04 -1.88574023e-04 -2.66814461e-04 ... -9.52264204e-04
    -2.65328846e-04 -5.34682877e-04]
   ...
   [-4.90849758e-04  1.02450938e-04  3.03380229e-04 ... -4.35112482e-04
     6.04583223e-04  3.08632837e-05]
   [ 3.52874524e-04  5.68844776e-05 -6.24837979e-04 ...  6.51760000e-04
    -5.87595674e-05  5.09852162e-04]
   [ 5.41345790e-04 -4.63844561e-05  7.51714714e-04 ... -4.60815609e-04
    -2.20239300e-04  2.40613496e-04]]

  [[ 3.27551807e-04  7.24411440e-04 -9.39572499e-05 ...  3.84310855e-04
    -1.31173793e-04  7.34562758e-04]
   [ 1.02005303e-03 -6.23952120e-04 -5.43600240e-04 ... -4.79716232e-04
    -9.75091262e-04 -2.73508937e-05]
   [ 7.04614482e-04  7.59290496e-04  2.14824103e-04 ... -1.59532682e-04
    -3.19193459e-04 -1.97617445e-05]
   ...
   [-2.00856445e-04 -1.91217446e-04 -2.14038370e-04 ...  3.70694809e-04
     1.21008347e-05  1.09239590e-04]
   [-6.15167284e-04  4.41402557e-04  5.20115920e-05 ... -1.44298307e-04
    -8.52460705e-04  6.07681157e-05]
   [-5.62508607e-04  3.61819613e-04  3.50547569e-04 ... -6.48235289e-05
    -3.50237836e-05  3.06421054e-04]]

  [[ 5.57001901e-04 -3.07759142e-04 -9.53419172e-04 ...  3.50654381e-04
     4.62598331e-04 -1.63066915e-03]
   [-3.71156279e-04 -7.82564139e-04 -5.80767169e-04 ...  1.14238431e-04
     1.12071983e-04 -1.05862969e-04]
   [-6.16229588e-04 -1.02905461e-04 -2.48026193e-04 ... -4.09886750e-04
    -1.33882756e-04 -5.78863655e-04]
   ...
   [-3.29901306e-04  4.74213056e-04  5.47846896e-04 ...  2.58633915e-04
     9.21961053e-05 -4.21171441e-04]
   [-2.87629702e-04  3.22918677e-04  7.40511989e-05 ... -2.68957223e-04
     9.22874848e-04 -1.74389738e-04]
   [-2.50063165e-04 -1.53250741e-03 -3.31756529e-06 ...  4.79415818e-04
     2.12766671e-04  2.44963338e-04]]]]

 but returned output is 

-0.4291725599236313

 difference is 

[[[[-0.42915903 -0.42844986 -0.42997549 ... -0.42845023 -0.42959569
    -0.42887439]
   [-0.4282745  -0.42950128 -0.42939628 ... -0.42906105 -0.42880664
    -0.42897195]
   [-0.42889536 -0.42916956 -0.42937401 ... -0.42916649 -0.42927085
    -0.42987476]
   ...
   [-0.42878573 -0.42949231 -0.42920198 ... -0.42941472 -0.42904121
    -0.42906473]
   [-0.42936112 -0.42999059 -0.42900484 ... -0.42868282 -0.42815653
    -0.42949213]
   [-0.42931229 -0.42913198 -0.42902005 ... -0.42908941 -0.42995725
    -0.42862861]]

  [[-0.42906045 -0.42862274 -0.42912214 ... -0.42952728 -0.42936072
    -0.42897312]
   [-0.4292634  -0.42872112 -0.42921775 ... -0.42926609 -0.42855745
    -0.42962711]
   [-0.42885784 -0.4282565  -0.43002299 ... -0.42973158 -0.42870814
    -0.42991762]
   ...
   [-0.42953873 -0.4295274  -0.42926329 ... -0.42849964 -0.42927549
    -0.42981098]
   [-0.42904538 -0.42997783 -0.42896075 ... -0.42946214 -0.42902362
    -0.42965639]
   [-0.42880426 -0.42961102 -0.42865396 ... -0.42997693 -0.42799118
    -0.4291884 ]]

  [[-0.42818312 -0.42891983 -0.42879357 ... -0.4282982  -0.42891365
    -0.42850763]
   [-0.42895346 -0.42902404 -0.4293889  ... -0.42917242 -0.42911384
    -0.42951062]
   [-0.42983756 -0.42932662 -0.42838113 ... -0.4290484  -0.4294501
    -0.42937578]
   ...
   [-0.42984794 -0.42925617 -0.42907577 ... -0.42980934 -0.42846586
    -0.429101  ]
   [-0.42947105 -0.42899095 -0.42941309 ... -0.42931624 -0.42901947
    -0.42948828]
   [-0.42884782 -0.42870837 -0.42912664 ... -0.42874442 -0.42919303
    -0.42970713]]]


 [[[-0.42811911 -0.42839744 -0.42949645 ... -0.42927584 -0.42928613
    -0.42898633]
   [-0.42990442 -0.43005065 -0.42896871 ... -0.42976023 -0.42870578
    -0.42840595]
   [-0.42908946 -0.43013697 -0.42879226 ... -0.42831655 -0.42946222
    -0.42899468]
   ...
   [-0.42942046 -0.42986451 -0.42867702 ... -0.42897118 -0.43020188
    -0.42949646]
   [-0.4286387  -0.42839117 -0.42964303 ... -0.4294172  -0.42899285
    -0.42903168]
   [-0.42901512 -0.42923437 -0.42889387 ... -0.42896807 -0.42934664
    -0.428594  ]]

  [[-0.42875518 -0.42883991 -0.4291998  ... -0.42889816 -0.42967865
    -0.4298105 ]
   [-0.42881231 -0.43005665 -0.42865602 ... -0.42920673 -0.42931946
    -0.42858161]
   [-0.42933121 -0.42872666 -0.42873925 ... -0.42979552 -0.43034285
    -0.42899622]
   ...
   [-0.42861244 -0.42931502 -0.42931563 ... -0.42891779 -0.429748
    -0.42882778]
   [-0.42949816 -0.43008229 -0.42860209 ... -0.42902127 -0.42885366
    -0.42958664]
   [-0.42909639 -0.42882305 -0.42908639 ... -0.42912767 -0.42884908
    -0.42920957]]

  [[-0.42852917 -0.4290033  -0.42869137 ... -0.42938822 -0.42927691
    -0.42842784]
   [-0.42893431 -0.42911541 -0.42956636 ... -0.42876357 -0.42898297
    -0.42902867]
   [-0.42977551 -0.428919   -0.42944014 ... -0.42929511 -0.42929634
    -0.42953196]
   ...
   [-0.42931926 -0.42919681 -0.42897485 ... -0.42961558 -0.42970847
    -0.42937898]
   [-0.4295322  -0.42895077 -0.43008113 ... -0.42971687 -0.4290255
    -0.42883326]
   [-0.43001756 -0.42924509 -0.42955007 ... -0.42858756 -0.42823225
    -0.42896203]]]


 [[[-0.42840674 -0.4297917  -0.42908544 ... -0.42941266 -0.42944609
    -0.42949826]
   [-0.42967233 -0.42992958 -0.42954151 ... -0.4293486  -0.42968548
    -0.42996   ]
   [-0.42948704 -0.4290459  -0.42802726 ... -0.42932266 -0.42926863
    -0.42920823]
   ...
   [-0.43045811 -0.42946889 -0.429589   ... -0.42925252 -0.42882164
    -0.4285243 ]
   [-0.42852368 -0.43012823 -0.42940981 ... -0.4297305  -0.42879951
    -0.42993627]
   [-0.4297031  -0.42855086 -0.4286318  ... -0.42920573 -0.42798407
    -0.42919787]]

  [[-0.42902314 -0.430115   -0.42881066 ... -0.42930123 -0.42904969
    -0.42958593]
   [-0.42872265 -0.43026558 -0.42835704 ... -0.42863549 -0.42927374
    -0.42915485]
   [-0.42973162 -0.42900957 -0.42850896 ... -0.42928264 -0.43021623
    -0.42893685]
   ...
   [-0.42899702 -0.42921459 -0.42926132 ... -0.4291912  -0.42943758
    -0.42945145]
   [-0.42907111 -0.42907935 -0.42974967 ... -0.42936406 -0.42922035
    -0.42850092]
   [-0.42959982 -0.42923918 -0.42939056 ... -0.4288282  -0.42978753
    -0.42952073]]

  [[-0.42932341 -0.4289498  -0.42853539 ... -0.42924929 -0.42845404
    -0.42924195]
   [-0.42835586 -0.42976949 -0.42924328 ... -0.42940202 -0.42923212
    -0.42870445]
   [-0.42938006 -0.42889657 -0.42833123 ... -0.42914145 -0.42933824
    -0.42936963]
   ...
   [-0.4290409  -0.42889184 -0.42903309 ... -0.42881259 -0.42817331
    -0.42960698]
   [-0.42937641 -0.42872523 -0.42904406 ... -0.42924929 -0.42980218
    -0.4297898 ]
   [-0.42858914 -0.42798458 -0.42888812 ... -0.4284483  -0.42881294
    -0.4285546 ]]]


 ...


 [[[-0.42922418 -0.42920136 -0.42876232 ... -0.42834447 -0.42865655
    -0.42941169]
   [-0.42922257 -0.42912721 -0.42992793 ... -0.42853529 -0.42975323
    -0.4301517 ]
   [-0.42879355 -0.42840825 -0.42939961 ... -0.42992925 -0.42942934
    -0.42953559]
   ...
   [-0.42942363 -0.42799662 -0.42956043 ... -0.42816084 -0.42955249
    -0.42916597]
   [-0.42790477 -0.42921465 -0.428765   ... -0.42860803 -0.42810982
    -0.42869557]
   [-0.42861884 -0.42891635 -0.42948442 ... -0.42825737 -0.42952854
    -0.42833403]]

  [[-0.42894612 -0.42867807 -0.42901256 ... -0.42969013 -0.42929015
    -0.42917663]
   [-0.42961137 -0.42975705 -0.42754106 ... -0.42915652 -0.42929175
    -0.42976755]
   [-0.42941476 -0.4299581  -0.42891731 ... -0.42928915 -0.42929554
    -0.42925957]
   ...
   [-0.42945736 -0.42781555 -0.42915196 ... -0.42894244 -0.42842531
    -0.4293703 ]
   [-0.42834729 -0.43007083 -0.42877441 ... -0.42921102 -0.42848049
    -0.42855443]
   [-0.42904926 -0.42865844 -0.42880982 ... -0.42952466 -0.42882106
    -0.42862036]]

  [[-0.4290085  -0.42939151 -0.42908743 ... -0.43030378 -0.4291509
    -0.42950548]
   [-0.42901276 -0.42850851 -0.42906075 ... -0.43001555 -0.42855962
    -0.42856625]
   [-0.42941565 -0.42924994 -0.42956162 ... -0.42875359 -0.4288611
    -0.42858695]
   ...
   [-0.42917392 -0.42859166 -0.42938761 ... -0.42896895 -0.42895462
    -0.42879619]
   [-0.42974299 -0.42821713 -0.42977549 ... -0.42906351 -0.4287582
    -0.42911415]
   [-0.42890821 -0.4288832  -0.42900622 ... -0.42856647 -0.42803459
    -0.42902692]]]


 [[[-0.42915524 -0.42851857 -0.42976349 ... -0.43012453 -0.42900006
    -0.4284679 ]
   [-0.42915233 -0.42879724 -0.4294507  ... -0.42859259 -0.42932632
    -0.42935712]
   [-0.428763   -0.42865129 -0.42908613 ... -0.42736676 -0.42910092
    -0.43006258]
   ...
   [-0.42904938 -0.42961727 -0.42896643 ... -0.42873749 -0.42896097
    -0.42913953]
   [-0.42911345 -0.42892732 -0.42839254 ... -0.42881709 -0.42980416
    -0.42898214]
   [-0.42928364 -0.42895143 -0.42911337 ... -0.42787185 -0.42856378
    -0.42850683]]

  [[-0.42893248 -0.42943441 -0.42837707 ... -0.42948832 -0.42807429
    -0.42828589]
   [-0.4284228  -0.42955157 -0.42888831 ... -0.42904232 -0.42935253
    -0.42853361]
   [-0.42935292 -0.42947953 -0.4295431  ... -0.42907823 -0.42839328
    -0.43001608]
   ...
   [-0.42851569 -0.42795286 -0.42934944 ... -0.42882482 -0.42947583
    -0.42868108]
   [-0.42947619 -0.42941405 -0.42876384 ... -0.4292626  -0.4289927
    -0.43024657]
   [-0.4295345  -0.42984763 -0.42990937 ... -0.42931046 -0.42964579
    -0.42845351]]

  [[-0.42916193 -0.42912259 -0.42848656 ... -0.42900138 -0.42987312
    -0.42946712]
   [-0.42900719 -0.42934038 -0.42883239 ... -0.42928437 -0.42922094
    -0.42957022]
   [-0.42946705 -0.42908456 -0.42919445 ... -0.42866612 -0.4291847
    -0.42920223]
   ...
   [-0.42926669 -0.42937429 -0.42901183 ... -0.42834615 -0.42911717
    -0.42899277]
   [-0.42840736 -0.43006054 -0.4288211  ... -0.4292923  -0.42951477
    -0.42862915]
   [-0.42985641 -0.42887349 -0.42954939 ... -0.42900715 -0.43006936
    -0.42868595]]]


 [[[-0.42964092 -0.42965055 -0.42882238 ... -0.4283172  -0.42926953
    -0.42915717]
   [-0.42925732 -0.42938042 -0.42950244 ... -0.42850564 -0.42850183
    -0.42903354]
   [-0.42863458 -0.42898399 -0.42890575 ... -0.4282203  -0.42890723
    -0.42863788]
   ...
   [-0.42868171 -0.42927501 -0.42947594 ... -0.42873745 -0.42977714
    -0.42920342]
   [-0.42952543 -0.42922944 -0.42854772 ... -0.42982432 -0.4291138
    -0.42968241]
   [-0.42971391 -0.42912618 -0.42992427 ... -0.42871174 -0.42895232
    -0.42941317]]

  [[-0.42950011 -0.42989697 -0.4290786  ... -0.42955687 -0.42904139
    -0.42990712]
   [-0.43019261 -0.42854861 -0.42862896 ... -0.42869284 -0.42819747
    -0.42914521]
   [-0.42987717 -0.42993185 -0.42938738 ... -0.42901303 -0.42885337
    -0.4291528 ]
   ...
   [-0.4289717  -0.42898134 -0.42895852 ... -0.42954325 -0.42918466
    -0.4292818 ]
   [-0.42855739 -0.42961396 -0.42922457 ... -0.42902826 -0.4283201
    -0.42923333]
   [-0.42861005 -0.42953438 -0.42952311 ... -0.42910774 -0.42913754
    -0.42947898]]

  [[-0.42972956 -0.4288648  -0.42821914 ... -0.42952321 -0.42963516
    -0.42754189]
   [-0.4288014  -0.42839    -0.42859179 ... -0.4292868  -0.42928463
    -0.4290667 ]
   [-0.42855633 -0.42906965 -0.42892453 ... -0.42876267 -0.42903868
    -0.4285937 ]
   ...
   [-0.42884266 -0.42964677 -0.42972041 ... -0.42943119 -0.42926476
    -0.42875139]
   [-0.42888493 -0.42949548 -0.42924661 ... -0.4289036  -0.43009543
    -0.42899817]
   [-0.4289225  -0.42764005 -0.42916924 ... -0.42965198 -0.42938533
    -0.42941752]]]]

In [ ]:
from mlp.test_methods import test_L2_Penalty


call_test, call_output, call_correct, \
grad_test, grad_output, grad_correct = test_L2_Penalty()


assert call_test == 1.0, (
'The call function for L2 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(call_correct, call_output, call_output-call_correct)
)

print("L2 Penalty Call Functionality Test Passed")

assert grad_test == 1.0, (
'The grad function for L2 Penalty test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grad_correct, grad_output, grad_output-grad_correct, grad_output/grad_correct)
)



print("L2 Penalty Grad Function Test Passed")